# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui_layout2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1683, 818)
        Window.setStyleSheet("/*\n"
"ElegantDark Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 17/04/2018\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/ElegantDark.qss\n"
"*/\n"
"\n"
"QMainWindow {\n"
"    background-color:rgb(82, 82, 82);\n"
"}\n"
"QTextEdit {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QDoubleSpinBox {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color:rgb(255,255,255);    \n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:rgb(77,77,77);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(0, 170, 127);\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(82, 82, 82);\n"
"}\n"
"QMenuBar::item {\n"
"    color:rgb(223,219,210);\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background:rgb(115, 115, 115);\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    padding-left:18px;\n"
"    padding-right:8px;\n"
"    padding-top:2px;\n"
"    padding-bottom:3px;\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(78,78,78);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu{\n"
"    background-color:rgb(78,78,78);\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:rgb(101,101,101);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding:2px;\n"
"    color:rgb(250,250,250);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"      border-top-right-radius:4px;\n"
"   border-top-left-radius:4px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-bottom-color: rgb(101,101,101);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(101,101,101);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"        margin-top: 1px;\n"
"        margin-right: 1px;\n"
"}\n"
"QCheckBox {\n"
"    color:rgb(223,219,210);\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(180,180,180);\n"
"      background-color: rgb(0, 170, 127)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(240,240,240);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1681, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1671, 731))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(40)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 3, 1, 1)
        self.lossProbability = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lossProbability.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lossProbability.setFont(font)
        self.lossProbability.setObjectName("lossProbability")
        self.gridLayout.addWidget(self.lossProbability, 5, 7, 1, 1)
        self.numberOfQubits = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.numberOfQubits.setFont(font)
        self.numberOfQubits.setMinimum(1000)
        self.numberOfQubits.setMaximum(999999999)
        self.numberOfQubits.setSingleStep(10)
        self.numberOfQubits.setProperty("value", 1000000)
        self.numberOfQubits.setObjectName("numberOfQubits")
        self.gridLayout.addWidget(self.numberOfQubits, 6, 4, 1, 1)
        self.finalKeyLength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.finalKeyLength.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.finalKeyLength.setFont(font)
        self.finalKeyLength.setObjectName("finalKeyLength")
        self.gridLayout.addWidget(self.finalKeyLength, 1, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 5, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 5, 7, 1)
        self.perturbationsEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perturbationsEnabled.setFont(font)
        self.perturbationsEnabled.setText("")
        self.perturbationsEnabled.setChecked(True)
        self.perturbationsEnabled.setObjectName("perturbationsEnabled")
        self.gridLayout.addWidget(self.perturbationsEnabled, 3, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 7, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 3, 1, 1)
        self.generationUncertainty = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.generationUncertainty.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.generationUncertainty.setFont(font)
        self.generationUncertainty.setMaximum(7.0)
        self.generationUncertainty.setSingleStep(0.1)
        self.generationUncertainty.setProperty("value", 0.13)
        self.generationUncertainty.setObjectName("generationUncertainty")
        self.gridLayout.addWidget(self.generationUncertainty, 7, 1, 1, 1)
        self.protocolDropdown = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.protocolDropdown.setFont(font)
        self.protocolDropdown.setObjectName("protocolDropdown")
        self.protocolDropdown.addItem("")
        self.protocolDropdown.addItem("")
        self.protocolDropdown.addItem("")
        self.protocolDropdown.addItem("")
        self.gridLayout.addWidget(self.protocolDropdown, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 1)
        self.fiberLoss = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiberLoss.setFont(font)
        self.fiberLoss.setMaximum(100.0)
        self.fiberLoss.setSingleStep(0.1)
        self.fiberLoss.setProperty("value", 0.53)
        self.fiberLoss.setObjectName("fiberLoss")
        self.gridLayout.addWidget(self.fiberLoss, 4, 1, 1, 1)
        self.viewSample = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.viewSample.setFont(font)
        self.viewSample.setObjectName("viewSample")
        self.gridLayout.addWidget(self.viewSample, 7, 6, 1, 2)
        self.eavesdroppingEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eavesdroppingEnabled.setFont(font)
        self.eavesdroppingEnabled.setText("")
        self.eavesdroppingEnabled.setObjectName("eavesdroppingEnabled")
        self.gridLayout.addWidget(self.eavesdroppingEnabled, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.lossesEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lossesEnabled.setFont(font)
        self.lossesEnabled.setMouseTracking(True)
        self.lossesEnabled.setAutoFillBackground(False)
        self.lossesEnabled.setText("")
        self.lossesEnabled.setChecked(True)
        self.lossesEnabled.setObjectName("lossesEnabled")
        self.gridLayout.addWidget(self.lossesEnabled, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 3, 1, 1)
        self.S = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.S.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.S.setFont(font)
        self.S.setObjectName("S")
        self.gridLayout.addWidget(self.S, 4, 7, 1, 1)
        self.generationRate = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.generationRate.setFont(font)
        self.generationRate.setToolTipDuration(-1)
        self.generationRate.setMaximum(999999999999999.0)
        self.generationRate.setProperty("value", 72.6)
        self.generationRate.setObjectName("generationRate")
        self.gridLayout.addWidget(self.generationRate, 1, 1, 1, 1)
        self.perturbProbability = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.perturbProbability.setFont(font)
        self.perturbProbability.setMaximum(100.0)
        self.perturbProbability.setProperty("value", 5.0)
        self.perturbProbability.setObjectName("perturbProbability")
        self.gridLayout.addWidget(self.perturbProbability, 6, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 6, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 6, 6, 1, 2)
        self.generationUncertaintyEnabled = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.generationUncertaintyEnabled.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generationUncertaintyEnabled.setFont(font)
        self.generationUncertaintyEnabled.setText("")
        self.generationUncertaintyEnabled.setChecked(True)
        self.generationUncertaintyEnabled.setObjectName("generationUncertaintyEnabled")
        self.gridLayout.addWidget(self.generationUncertaintyEnabled, 5, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.detectorLoss = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.detectorLoss.setFont(font)
        self.detectorLoss.setMaximum(100.0)
        self.detectorLoss.setProperty("value", 11.0)
        self.detectorLoss.setObjectName("detectorLoss")
        self.gridLayout.addWidget(self.detectorLoss, 5, 1, 1, 1)
        self.fiberLength = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fiberLength.setFont(font)
        self.fiberLength.setMaximum(1000.0)
        self.fiberLength.setProperty("value", 18.0)
        self.fiberLength.setObjectName("fiberLength")
        self.gridLayout.addWidget(self.fiberLength, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.QBER = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.QBER.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.QBER.setFont(font)
        self.QBER.setObjectName("QBER")
        self.gridLayout.addWidget(self.QBER, 3, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 6, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 6, 1, 1)
        self.uncertaintyEnabledLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uncertaintyEnabledLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uncertaintyEnabledLabel.setFont(font)
        self.uncertaintyEnabledLabel.setObjectName("uncertaintyEnabledLabel")
        self.gridLayout.addWidget(self.uncertaintyEnabledLabel, 5, 3, 1, 1)
        self.crossCheckFraction = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.crossCheckFraction.setFont(font)
        self.crossCheckFraction.setMaximum(100.0)
        self.crossCheckFraction.setProperty("value", 10.0)
        self.crossCheckFraction.setObjectName("crossCheckFraction")
        self.gridLayout.addWidget(self.crossCheckFraction, 7, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.keyGenerationRate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.keyGenerationRate.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.keyGenerationRate.setFont(font)
        self.keyGenerationRate.setObjectName("keyGenerationRate")
        self.gridLayout.addWidget(self.keyGenerationRate, 2, 7, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.sourceEfficiency = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sourceEfficiency.setFont(font)
        self.sourceEfficiency.setMaximum(100.0)
        self.sourceEfficiency.setProperty("value", 5.8)
        self.sourceEfficiency.setObjectName("sourceEfficiency")
        self.gridLayout.addWidget(self.sourceEfficiency, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 8, 0, 1, 7)
        self.abortButtonSingle = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.abortButtonSingle.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.abortButtonSingle.setFont(font)
        self.abortButtonSingle.setObjectName("abortButtonSingle")
        self.gridLayout.addWidget(self.abortButtonSingle, 8, 7, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1511, 601))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setSpacing(40)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yParameter = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yParameter.setFont(font)
        self.yParameter.setObjectName("yParameter")
        self.yParameter.addItem("")
        self.yParameter.addItem("")
        self.yParameter.addItem("")
        self.gridLayout_2.addWidget(self.yParameter, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 4, 0, 1, 1)
        self.numberOfPoints = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.numberOfPoints.setFont(font)
        self.numberOfPoints.setMinimum(1)
        self.numberOfPoints.setMaximum(99999999)
        self.numberOfPoints.setProperty("value", 10)
        self.numberOfPoints.setObjectName("numberOfPoints")
        self.gridLayout_2.addWidget(self.numberOfPoints, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 2)
        self.label31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label31.setFont(font)
        self.label31.setObjectName("label31")
        self.gridLayout_2.addWidget(self.label31, 5, 0, 1, 1)
        self.xParameter = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xParameter.setFont(font)
        self.xParameter.setObjectName("xParameter")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.xParameter.addItem("")
        self.gridLayout_2.addWidget(self.xParameter, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 3, 0, 1, 1)
        self.multiProgressBar = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.multiProgressBar.setFont(font)
        self.multiProgressBar.setProperty("value", 100)
        self.multiProgressBar.setObjectName("multiProgressBar")
        self.gridLayout_2.addWidget(self.multiProgressBar, 7, 0, 1, 4)
        self.multiRunButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.multiRunButton.setFont(font)
        self.multiRunButton.setObjectName("multiRunButton")
        self.gridLayout_2.addWidget(self.multiRunButton, 6, 0, 1, 1)
        self.startValue = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startValue.setFont(font)
        self.startValue.setMaximum(999999999.0)
        self.startValue.setObjectName("startValue")
        self.gridLayout_2.addWidget(self.startValue, 3, 1, 1, 1)
        self.endValue = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.endValue.setFont(font)
        self.endValue.setMaximum(999999999.0)
        self.endValue.setObjectName("endValue")
        self.gridLayout_2.addWidget(self.endValue, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 2, 6, 1)
        self.multiPlot = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.multiPlot.setFont(font)
        self.multiPlot.setText("")
        self.multiPlot.setScaledContents(True)
        self.multiPlot.setObjectName("multiPlot")
        self.gridLayout_2.addWidget(self.multiPlot, 1, 3, 6, 1)
        self.abortButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.abortButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.abortButton.setFont(font)
        self.abortButton.setObjectName("abortButton")
        self.gridLayout_2.addWidget(self.abortButton, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1683, 23))
        self.menubar.setObjectName("menubar")
        Window.setMenuBar(self.menubar)

        self.retranslateUi(Window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "QKD Simulator"))
        self.label_12.setToolTip(_translate("Window", "<html><head/><body><p>The number of qubits to use for the simulation.</p></body></html>"))
        self.label_12.setText(_translate("Window", "Number of qubits"))
        self.lossProbability.setToolTip(_translate("Window", "<html><head/><body><p>The combined efficiency of source, fiber and detector.</p></body></html>"))
        self.numberOfQubits.setToolTip(_translate("Window", "<html><head/><body><p>The number of qubits to use for the simulation.</p></body></html>"))
        self.finalKeyLength.setToolTip(_translate("Window", "<html><head/><body><p>The length of the final key produced.</p></body></html>"))
        self.label_19.setToolTip(_translate("Window", "<html><head/><body><p>The combined efficiency of source, fiber and detector.</p></body></html>"))
        self.label_19.setText(_translate("Window", "Combined efficiency"))
        self.label_15.setToolTip(_translate("Window", "<html><head/><body><p>The achieved key generation rate of the simulation.</p></body></html>"))
        self.label_15.setText(_translate("Window", "Key rate"))
        self.perturbationsEnabled.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable random perturbations, e.g. perturb probability is zero if disabled.</p></body></html>"))
        self.label_20.setToolTip(_translate("Window", "<html><head/><body><p>The efficiency of the detector.</p></body></html>"))
        self.label_20.setText(_translate("Window", "Detector efficiency"))
        self.label_4.setToolTip(_translate("Window", "The generation rate of the quantum source before losses."))
        self.label_4.setText(_translate("Window", "Source generation rate"))
        self.label_11.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable random perturbations, e.g. perturb probability is zero if disabled.</p></body></html>"))
        self.label_11.setText(_translate("Window", "Perturbations enabled"))
        self.generationUncertainty.setToolTip(_translate("Window", "<html><head/><body><p>The mean deviation of each qubit from the desired state of polarisation (SOP). This emulates imperfect state preperation and drift compensation.</p></body></html>"))
        self.generationUncertainty.setSuffix(_translate("Window", " rad"))
        self.protocolDropdown.setToolTip(_translate("Window", "<html><head/><body><p>Which protocol to use for the simulation.</p></body></html>"))
        self.protocolDropdown.setItemText(0, _translate("Window", "BB84"))
        self.protocolDropdown.setItemText(1, _translate("Window", "B92"))
        self.protocolDropdown.setItemText(2, _translate("Window", "E91"))
        self.protocolDropdown.setItemText(3, _translate("Window", "BBM92"))
        self.label_7.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable eavesdropping.</p></body></html>"))
        self.label_7.setText(_translate("Window", "Eavesdropping enabled"))
        self.fiberLoss.setToolTip(_translate("Window", "<html><head/><body><p>The losses in the fiber per km.</p></body></html>"))
        self.fiberLoss.setSuffix(_translate("Window", " db/km"))
        self.viewSample.setToolTip(_translate("Window", "<html><head/><body><p>Displays a sample of the quantum circuits created for a simulation.</p></body></html>"))
        self.viewSample.setText(_translate("Window", "View sample"))
        self.eavesdroppingEnabled.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable eavesdropping.</p></body></html>"))
        self.label_6.setToolTip(_translate("Window", "<html><head/><body><p>The mean deviation of each qubit from the desired state of polarisation (SOP). This emulates imperfect state preperation and drift compensation.</p></body></html>"))
        self.label_6.setText(_translate("Window", "SOP mean deviation"))
        self.label.setText(_translate("Window", "System parameters"))
        self.lossesEnabled.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable all losses, e.g. source efficiency, fiber loss and detector efficiency are zero if disabled. Remember that since losses are normally very high (&gt;90%) simulations take a long time with losses disabled.</p></body></html>"))
        self.label_17.setToolTip(_translate("Window", "<html><head/><body><p>The quantum bit error rate (QBER) achieved in the simulation.</p></body></html>"))
        self.label_17.setText(_translate("Window", "QBER"))
        self.label_5.setToolTip(_translate("Window", "<html><head/><body><p>The probability of a qubit having a random state when measured. This emulates uncompensated perturbations.</p></body></html>"))
        self.label_5.setText(_translate("Window", "Perturb probability"))
        self.label_13.setToolTip(_translate("Window", "<html><head/><body><p>The fraction of the final key used to calculate the QBER.</p></body></html>"))
        self.label_13.setText(_translate("Window", "QBER cross-check fraction"))
        self.S.setToolTip(_translate("Window", "<html><head/><body><p>The S statistic. Only applicable for the E91 protocol.</p></body></html>"))
        self.generationRate.setToolTip(_translate("Window", "<html><head/><body><p>The generation rate of the quantum source before losses.</p></body></html>"))
        self.generationRate.setWhatsThis(_translate("Window", "Test"))
        self.generationRate.setSuffix(_translate("Window", " MHz"))
        self.perturbProbability.setToolTip(_translate("Window", "<html><head/><body><p>The probability of a qubit having a random state when measured. This emulates uncompensated perturbations.</p></body></html>"))
        self.perturbProbability.setSuffix(_translate("Window", " %"))
        self.label_18.setToolTip(_translate("Window", "<html><head/><body><p>The S statistic. Only applicable for the E91 protocol.</p></body></html>"))
        self.label_18.setText(_translate("Window", "S"))
        self.runButton.setText(_translate("Window", "Run simulation"))
        self.generationUncertaintyEnabled.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable uncertainty in the state of polarisation (SOP) of each qubit, e.g. SOP mean deviation is zero if disabled.</p></body></html>"))
        self.label_10.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable all losses, e.g. source efficiency, fiber loss and detector efficiency are zero if disabled. Remember that since losses are normally very high (&gt;90%) simulations take a long time with losses disabled.</p></body></html>"))
        self.label_10.setText(_translate("Window", "Losses enabled"))
        self.detectorLoss.setToolTip(_translate("Window", "<html><head/><body><p>The efficiency of the detector.</p></body></html>"))
        self.detectorLoss.setSuffix(_translate("Window", " %"))
        self.fiberLength.setToolTip(_translate("Window", "<html><head/><body><p>The length of the fiber used.</p></body></html>"))
        self.fiberLength.setSuffix(_translate("Window", " km"))
        self.label_8.setToolTip(_translate("Window", "<html><head/><body><p>Which protocol to use for the simulation.</p></body></html>"))
        self.label_8.setText(_translate("Window", "Protocol "))
        self.QBER.setToolTip(_translate("Window", "<html><head/><body><p>The quantum bit error rate (QBER) achieved in the simulation.</p></body></html>"))
        self.label_16.setText(_translate("Window", "Results"))
        self.label_14.setToolTip(_translate("Window", "<html><head/><body><p>The length of the final key produced.</p></body></html>"))
        self.label_14.setText(_translate("Window", "Key length"))
        self.uncertaintyEnabledLabel.setToolTip(_translate("Window", "<html><head/><body><p>Enable or disable uncertainty in the state of polarisation (SOP) of each qubit, e.g. SOP mean deviation is zero if disabled.</p></body></html>"))
        self.uncertaintyEnabledLabel.setText(_translate("Window", "SOP uncertainty enabled"))
        self.crossCheckFraction.setToolTip(_translate("Window", "<html><head/><body><p>The fraction of the final key used to calculate the QBER.</p></body></html>"))
        self.crossCheckFraction.setSuffix(_translate("Window", " %"))
        self.label_9.setText(_translate("Window", "Simulation settings"))
        self.label_3.setToolTip(_translate("Window", "<html><head/><body><p>The losses in the fiber per km.</p></body></html>"))
        self.label_3.setText(_translate("Window", "Fiber loss"))
        self.label_2.setToolTip(_translate("Window", "<html><head/><body><p>The length of the fiber used.</p></body></html>"))
        self.label_2.setText(_translate("Window", "Fiber length"))
        self.keyGenerationRate.setToolTip(_translate("Window", "<html><head/><body><p>The achieved key generation rate of the simulation.</p></body></html>"))
        self.label_21.setToolTip(_translate("Window", "<html><head/><body><p>The efficiency of the source.</p></body></html>"))
        self.label_21.setText(_translate("Window", "Source efficiency"))
        self.sourceEfficiency.setToolTip(_translate("Window", "<html><head/><body><p>The efficiency of the source.</p></body></html>"))
        self.sourceEfficiency.setSuffix(_translate("Window", " %"))
        self.abortButtonSingle.setText(_translate("Window", "Abort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Window", "Single simulation"))
        self.yParameter.setToolTip(_translate("Window", "<html><head/><body><p>Which result metric that is plotted.</p></body></html>"))
        self.yParameter.setItemText(0, _translate("Window", "Key length"))
        self.yParameter.setItemText(1, _translate("Window", "Key rate"))
        self.yParameter.setItemText(2, _translate("Window", "QBER"))
        self.label_26.setToolTip(_translate("Window", "<html><head/><body><p>Which result metric that is plotted.</p></body></html>"))
        self.label_26.setText(_translate("Window", "Select y-parameter"))
        self.label_24.setText(_translate("Window", "Results"))
        self.label_28.setToolTip(_translate("Window", "<html><head/><body><p>End point for the desired interval of x-parameter values. Set start value and end value to the same to produce multiple simulations of the same configuration.</p></body></html>"))
        self.label_28.setText(_translate("Window", "End value x"))
        self.numberOfPoints.setToolTip(_translate("Window", "<html><head/><body><p>The number of points desired from the given interval.</p></body></html>"))
        self.label_23.setText(_translate("Window", "Parameters"))
        self.label31.setToolTip(_translate("Window", "<html><head/><body><p>The number of points desired from the given interval.</p></body></html>"))
        self.label31.setText(_translate("Window", "Number of points"))
        self.xParameter.setToolTip(_translate("Window", "<html><head/><body><p>Which parameter to vary in the specified interval.</p></body></html>"))
        self.xParameter.setItemText(0, _translate("Window", "Fiber length"))
        self.xParameter.setItemText(1, _translate("Window", "Fiber loss"))
        self.xParameter.setItemText(2, _translate("Window", "Source generation rate"))
        self.xParameter.setItemText(3, _translate("Window", "Source efficiency"))
        self.xParameter.setItemText(4, _translate("Window", "Detector efficiency"))
        self.xParameter.setItemText(5, _translate("Window", "Perturb probability"))
        self.xParameter.setItemText(6, _translate("Window", "SOP mean deviation"))
        self.xParameter.setItemText(7, _translate("Window", "Cross check fraction"))
        self.label_25.setToolTip(_translate("Window", "<html><head/><body><p>Which parameter to vary in the specified interval.</p></body></html>"))
        self.label_25.setText(_translate("Window", "Select x-parameter"))
        self.label_27.setToolTip(_translate("Window", "<html><head/><body><p>Starting point for the desired interval of x-parameter values. Set start value and end value to the same to produce multiple simulations of the same configuration.</p></body></html>"))
        self.label_27.setText(_translate("Window", "Start value x"))
        self.multiRunButton.setText(_translate("Window", "Run simulations"))
        self.startValue.setToolTip(_translate("Window", "<html><head/><body><p>Starting point for the desired interval of x-parameter values. Set start value and end value to the same to produce multiple simulations of the same configuration.</p></body></html>"))
        self.startValue.setSuffix(_translate("Window", " km"))
        self.endValue.setToolTip(_translate("Window", "<html><head/><body><p>End point for the desired interval of x-parameter values. Set start value and end value to the same to produce multiple simulations of the same configuration.</p></body></html>"))
        self.endValue.setSuffix(_translate("Window", " km"))
        self.abortButton.setText(_translate("Window", "Abort"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Window", "Multiple simulations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
